version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./outputs/data/:/app/outputs/data
      - ./outputs/logs/:/app/outputs/logs
    tty: true
    entrypoint: python yearly_data.py 